/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_claudiacortes_programación2;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.TransferHandler;

/**
 *
 * @author Claudia Cortes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        lbl_UML.setVisible(false);
        lbl_Diagrama.setVisible(false);
          this.setExtendedState(MAXIMIZED_BOTH);
        // lbl_FondoInicio.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_DiagramaClases = new javax.swing.JDialog();
        jd_UML = new javax.swing.JDialog();
        btn_Proceso = new javax.swing.JButton();
        btn_documento = new javax.swing.JButton();
        btn_Decision = new javax.swing.JButton();
        btn_SubPro = new javax.swing.JButton();
        btn_SeparadorV = new javax.swing.JButton();
        btn_InicioFin = new javax.swing.JButton();
        btn_datos = new javax.swing.JButton();
        btn_separador = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        pic1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jp_Drag = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jFrame1 = new javax.swing.JFrame();
        btn_DiagramaFlujo1 = new javax.swing.JButton();
        btn_DiagramaClases1 = new javax.swing.JButton();
        btn_Crear1 = new javax.swing.JButton();
        lbl_FondoInicio1 = new javax.swing.JLabel();
        lbl_UML1 = new javax.swing.JLabel();
        lbl_Diagrama1 = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        pp_OP = new javax.swing.JPopupMenu();
        jmi_color = new javax.swing.JMenuItem();
        jmi_texto = new javax.swing.JMenuItem();
        jmi_eliminar = new javax.swing.JMenuItem();
        jmi_fuente = new javax.swing.JMenuItem();
        btn_DiagramaFlujo = new javax.swing.JButton();
        btn_DiagramaClases = new javax.swing.JButton();
        btn_Crear = new javax.swing.JButton();
        lbl_FondoInicio = new javax.swing.JLabel();
        lbl_UML = new javax.swing.JLabel();
        lbl_Diagrama = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jd_DiagramaClases.setMinimumSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout jd_DiagramaClasesLayout = new javax.swing.GroupLayout(jd_DiagramaClases.getContentPane());
        jd_DiagramaClases.getContentPane().setLayout(jd_DiagramaClasesLayout);
        jd_DiagramaClasesLayout.setHorizontalGroup(
            jd_DiagramaClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jd_DiagramaClasesLayout.setVerticalGroup(
            jd_DiagramaClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        jd_UML.setBackground(new java.awt.Color(255, 255, 255));
        jd_UML.setMinimumSize(new java.awt.Dimension(600, 600));
        jd_UML.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Proceso.setBackground(new java.awt.Color(255, 255, 255));
        btn_Proceso.setFont(btn_Proceso.getFont().deriveFont((float)13));
        btn_Proceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UML/Proceso.png"))); // NOI18N
        btn_Proceso.setToolTipText("");
        btn_Proceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ProcesoMouseClicked(evt);
            }
        });
        btn_Proceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProcesoActionPerformed(evt);
            }
        });
        jd_UML.getContentPane().add(btn_Proceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, 70));

        btn_documento.setBackground(new java.awt.Color(255, 255, 255));
        btn_documento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UML/documentos.png"))); // NOI18N
        btn_documento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_documentoMouseClicked(evt);
            }
        });
        jd_UML.getContentPane().add(btn_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 110, 70));

        btn_Decision.setBackground(new java.awt.Color(255, 255, 255));
        btn_Decision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UML/if.png"))); // NOI18N
        btn_Decision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DecisionMouseClicked(evt);
            }
        });
        jd_UML.getContentPane().add(btn_Decision, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 100, 70));

        btn_SubPro.setBackground(new java.awt.Color(255, 255, 255));
        btn_SubPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UML/subpro.png"))); // NOI18N
        btn_SubPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SubProMouseClicked(evt);
            }
        });
        jd_UML.getContentPane().add(btn_SubPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 110, 80));

        btn_SeparadorV.setBackground(new java.awt.Color(255, 255, 255));
        btn_SeparadorV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UML/separadorV.png"))); // NOI18N
        btn_SeparadorV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SeparadorVMouseClicked(evt);
            }
        });
        jd_UML.getContentPane().add(btn_SeparadorV, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 140, 10));

        btn_InicioFin.setBackground(new java.awt.Color(255, 255, 255));
        btn_InicioFin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UML/in_fin.png"))); // NOI18N
        btn_InicioFin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_InicioFinMouseClicked(evt);
            }
        });
        jd_UML.getContentPane().add(btn_InicioFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 159, 30, 20));

        btn_datos.setBackground(new java.awt.Color(255, 255, 255));
        btn_datos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UML/datos.png"))); // NOI18N
        btn_datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_datosMouseClicked(evt);
            }
        });
        jd_UML.getContentPane().add(btn_datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 100, 60));

        btn_separador.setBackground(new java.awt.Color(255, 255, 255));
        btn_separador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UML/separador.png"))); // NOI18N
        btn_separador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_separadorMouseClicked(evt);
            }
        });
        jd_UML.getContentPane().add(btn_separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 20, 100));

        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setText("Color");
        jd_UML.getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));
        label1.getAccessibleContext().setAccessibleName("Estilo de fuente");

        label2.setText("Fuente");
        jd_UML.getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        label3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label3.setText("Tamaño");
        jd_UML.getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        label4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label4.setText("Estilo de fuente");
        jd_UML.getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        pic1.setText("proceso");
        jd_UML.getContentPane().add(pic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 140, 50));

        jLabel1.setText("jLabel1");
        jd_UML.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        jLabel2.setText("jLabel2");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jd_UML.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jp_Drag.setBackground(new java.awt.Color(153, 255, 255));
        jp_Drag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_DragMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_DragLayout = new javax.swing.GroupLayout(jp_Drag);
        jp_Drag.setLayout(jp_DragLayout);
        jp_DragLayout.setHorizontalGroup(
            jp_DragLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        jp_DragLayout.setVerticalGroup(
            jp_DragLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jd_UML.getContentPane().add(jp_Drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 920, 430));

        jMenu6.setText("Archivo");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("Insertar");
        jMenuBar2.add(jMenu7);

        jMenu8.setText("Diseño");
        jMenuBar2.add(jMenu8);

        jMenu9.setText("Datos");
        jMenuBar2.add(jMenu9);

        jMenu10.setText("Proceso");
        jMenuBar2.add(jMenu10);

        jMenu11.setText("Vista");
        jMenuBar2.add(jMenu11);

        jd_UML.setJMenuBar(jMenuBar2);

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setTitle("INICIO");
        jFrame1.setBackground(new java.awt.Color(255, 255, 255));
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_DiagramaFlujo1.setBackground(new java.awt.Color(255, 255, 255));
        btn_DiagramaFlujo1.setText("Diagramas de Flujo Basico");
        btn_DiagramaFlujo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DiagramaFlujo1MouseClicked(evt);
            }
        });
        btn_DiagramaFlujo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DiagramaFlujo1ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(btn_DiagramaFlujo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 136));

        btn_DiagramaClases1.setBackground(new java.awt.Color(255, 255, 255));
        btn_DiagramaClases1.setText("Diagrama de clases");
        btn_DiagramaClases1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DiagramaClases1MouseClicked(evt);
            }
        });
        jFrame1.getContentPane().add(btn_DiagramaClases1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 160, 136));

        btn_Crear1.setBackground(new java.awt.Color(255, 255, 255));
        btn_Crear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        btn_Crear1.setText("Crear");
        btn_Crear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Crear1MouseClicked(evt);
            }
        });
        jFrame1.getContentPane().add(btn_Crear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 170, 70));

        lbl_FondoInicio1.setText("FONDO");
        jFrame1.getContentPane().add(lbl_FondoInicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 320, 340));

        lbl_UML1.setText("UML");
        jFrame1.getContentPane().add(lbl_UML1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 320, 340));

        lbl_Diagrama1.setText("Diagrama");
        jFrame1.getContentPane().add(lbl_Diagrama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 320, 340));

        jMenu12.setText("Archivo");
        jMenuBar3.add(jMenu12);

        jMenu13.setText("Insertar");
        jMenuBar3.add(jMenu13);

        jMenu14.setText("Datos");
        jMenuBar3.add(jMenu14);

        jMenu15.setText("Procesos");
        jMenuBar3.add(jMenu15);

        jMenu16.setText("Vista");
        jMenuBar3.add(jMenu16);

        jFrame1.setJMenuBar(jMenuBar3);

        jmi_color.setText("Cambiar Color");
        jmi_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_colorActionPerformed(evt);
            }
        });
        pp_OP.add(jmi_color);

        jmi_texto.setText("Cambiar el Texto");
        jmi_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_textoActionPerformed(evt);
            }
        });
        pp_OP.add(jmi_texto);

        jmi_eliminar.setText("Eliminar");
        jmi_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarActionPerformed(evt);
            }
        });
        pp_OP.add(jmi_eliminar);

        jmi_fuente.setText("Cambiar Fuente");
        jmi_fuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_fuenteActionPerformed(evt);
            }
        });
        pp_OP.add(jmi_fuente);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_DiagramaFlujo.setBackground(new java.awt.Color(255, 255, 255));
        btn_DiagramaFlujo.setText("Diagramas de Flujo Basico");
        btn_DiagramaFlujo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DiagramaFlujoMouseClicked(evt);
            }
        });
        btn_DiagramaFlujo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DiagramaFlujoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_DiagramaFlujo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 136));

        btn_DiagramaClases.setBackground(new java.awt.Color(255, 255, 255));
        btn_DiagramaClases.setText("Diagrama de clases");
        btn_DiagramaClases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DiagramaClasesMouseClicked(evt);
            }
        });
        getContentPane().add(btn_DiagramaClases, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 160, 136));

        btn_Crear.setBackground(new java.awt.Color(255, 255, 255));
        btn_Crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        btn_Crear.setText("Crear");
        btn_Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CrearMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 170, 70));

        lbl_FondoInicio.setText("FONDO");
        getContentPane().add(lbl_FondoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 320, 340));

        lbl_UML.setText("UML");
        getContentPane().add(lbl_UML, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 320, 340));

        lbl_Diagrama.setText("Diagrama");
        getContentPane().add(lbl_Diagrama, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 320, 340));

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Insertar");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Datos");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Procesos");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Vista");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btn_DiagramaFlujoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DiagramaFlujoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DiagramaFlujoActionPerformed

    private void btn_CrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CrearMouseClicked
       
        if (Bandera == 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una opcion antes de iniciar a crear.");
        } else if (Bandera == 1) {
            jd_UML.show(true);
            this.jd_UML.setModal(true);
            jd_UML.pack();
            jd_UML.setLocationRelativeTo(this);
            
        } else if (Bandera == 2) {
            jd_DiagramaClases.show(true);

            this.jd_DiagramaClases.setModal(true);
            jd_DiagramaClases.pack();
            jd_DiagramaClases.setLocationRelativeTo(this);
        }
    }//GEN-LAST:event_btn_CrearMouseClicked

    private void btn_DiagramaFlujoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DiagramaFlujoMouseClicked
        lbl_FondoInicio.setVisible(false);
         
        lbl_Diagrama.setVisible(false);
        lbl_UML.setVisible(true);
        Bandera = 1;
        
    }//GEN-LAST:event_btn_DiagramaFlujoMouseClicked

    private void btn_DiagramaClasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DiagramaClasesMouseClicked
        new Lab();
        /* lbl_UML.setVisible(false);
        lbl_FondoInicio.setVisible(false);

        lbl_Diagrama.setVisible(true);
        Bandera = 2;*/
    }//GEN-LAST:event_btn_DiagramaClasesMouseClicked

    private void btn_ProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProcesoActionPerformed

    }//GEN-LAST:event_btn_ProcesoActionPerformed

    private void btn_ProcesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ProcesoMouseClicked
        JLabel lbl_Proceso;
        lbl_Proceso = new JLabel();
        lbl_Proceso.setOpaque(true);
      //  lbl_Proceso.
        lbl_Proceso.getName();
        lbl_Proceso.setName("Proceso" + Proceso);
        Proceso++;
        // System.out.println(lbl_Proceso);
        //System.out.println(lbl_Proceso.getName());
        // System.out.println("EL ERROR ESTA AQUI");
        this.jp_Drag.add(lbl_Proceso);
        lbl_Proceso.setBackground(Color.red);
        //  System.out.println(lbl_Proceso);

        lbl_Proceso.setLocation(10, 200);
        lbl_Proceso.setIcon(new ImageIcon(".\\src\\Imagenes\\UML\\proceso.png")); // NOI18N
        lbl_Proceso.setText("PROCESO");
        lbl_Proceso.setMaximumSize(new java.awt.Dimension(100, 100));
        lbl_Proceso.setMinimumSize(new Dimension(100, 100));
        lbl_Proceso.setLocation(new Point(20, 20));
        lbl_Proceso.setPreferredSize(new Dimension(50, 50));
        lbl_Proceso.setSize(100, 65);
        lbl_Proceso.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                if ((lbl_Proceso.getLocation().x + evt.getX() - lbl_Proceso.getWidth() / 2) >= 0
                        && (lbl_Proceso.getLocation().x + evt.getX() - lbl_Proceso.getWidth() / 2) <= 350) {
                    lbl_Proceso.setLocation(lbl_Proceso.getLocation().x + evt.getX() - lbl_Proceso.getWidth() / 2,
                            lbl_Proceso.getLocation().y + evt.getY() - lbl_Proceso.getHeight() / 2);
                    //System.out.println(lbl_Proceso);
                    // System.out.println(lbl_Proceso.getName());
                }// para que no se salga del rango

            }
        });  //agrega los label
        lbl_Proceso.addMouseListener(new MouseListener() {
            public void mouseClicked(MouseEvent evt) {
                if (evt.isMetaDown()) {
                    JL_actual = lbl_Proceso;
                    System.out.println(JL_actual);
                    System.out.println(lbl_Proceso.getText());
                    pp_OP.show(evt.getComponent(), evt.getX(), evt.getY());
                }
            }

            public void mouseEntered(MouseEvent arg0) {

            }

            public void mouseExited(MouseEvent arg0) {

            }

            public void mousePressed(MouseEvent arg0) {
            }

            public void mouseReleased(MouseEvent arg0) {
            }
        });

//panel.add(name);
        // añadimos al panel del dibujo

    }//GEN-LAST:event_btn_ProcesoMouseClicked

    private void btn_DiagramaFlujo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DiagramaFlujo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DiagramaFlujo1MouseClicked

    private void btn_DiagramaFlujo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DiagramaFlujo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DiagramaFlujo1ActionPerformed

    private void btn_DiagramaClases1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DiagramaClases1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DiagramaClases1MouseClicked

    private void btn_Crear1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Crear1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Crear1MouseClicked

    private void btn_DecisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DecisionMouseClicked
        JLabel lbl_if;
        lbl_if = new JLabel();
        lbl_if.setOpaque(true);
        lbl_if.getName();
        lbl_if.setName("lbo_if" + cont_If);
        cont_If++;
        //System.out.println(lbl_if);
        //System.out.println(lbl_if.getName());
        // System.out.println("EL ERROR ESTA AQUI");
        this.jp_Drag.add(lbl_if);
        lbl_if.setBackground(Color.red);
        // System.out.println(lbl_if);

        lbl_if.setLocation(10, 200);
        lbl_if.setIcon(new ImageIcon(".\\src\\Imagenes\\UML\\if.png")); // NOI18N
        lbl_if.setMaximumSize(new java.awt.Dimension(100, 100));
        lbl_if.setMinimumSize(new Dimension(100, 100));
        lbl_if.setLocation(new Point(20, 20));
        lbl_if.setPreferredSize(new Dimension(50, 50));
        lbl_if.setSize(100, 64);
        lbl_if.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                if ((lbl_if.getLocation().x + evt.getX() - lbl_if.getWidth() / 2) >= 0
                        && (lbl_if.getLocation().x + evt.getX() - lbl_if.getWidth() / 2) <= 350) {
                    lbl_if.setLocation(lbl_if.getLocation().x + evt.getX() - lbl_if.getWidth() / 2,
                            lbl_if.getLocation().y + evt.getY() - lbl_if.getHeight() / 2);
                    // System.out.println(lbl_if);
                    //System.out.println(lbl_if.getName());
                }// para que no se salga del rango

            }
        });  //agrega los label
        lbl_if.addMouseListener(new MouseListener() {
            public void mouseClicked(MouseEvent evt) {
                if (evt.isMetaDown()) {
                    JL_actual = lbl_if;
                    System.out.println(JL_actual);
                    pp_OP.show(evt.getComponent(), evt.getX(), evt.getY());
                }
            }

            public void mouseEntered(MouseEvent arg0) {

            }

            public void mouseExited(MouseEvent arg0) {

            }

            public void mousePressed(MouseEvent arg0) {
            }

            public void mouseReleased(MouseEvent arg0) {
            }
        });

    }//GEN-LAST:event_btn_DecisionMouseClicked

    private void btn_documentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_documentoMouseClicked
        JLabel lbl_documento;
        lbl_documento = new JLabel();
        lbl_documento.setOpaque(true);
        lbl_documento.getName();
        lbl_documento.setName("lbl_documento" + documentos);
        documentos++;
        // System.out.println(lbl_documento);
        //System.out.println(lbl_documento.getName());
        // System.out.println("EL ERROR ESTA AQUI");
        this.jp_Drag.add(lbl_documento);
        lbl_documento.setBackground(Color.red);
        // System.out.println(lbl_documento);

        lbl_documento.setLocation(10, 200);
        lbl_documento.setIcon(new ImageIcon(".\\src\\Imagenes\\UML\\documentos.png")); // NOI18N
        lbl_documento.setMaximumSize(new java.awt.Dimension(100, 100));
        lbl_documento.setMinimumSize(new Dimension(100, 100));
        lbl_documento.setLocation(new Point(20, 20));
        lbl_documento.setPreferredSize(new Dimension(50, 50));
        lbl_documento.setSize(100, 68);
        lbl_documento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                if ((lbl_documento.getLocation().x + evt.getX() - lbl_documento.getWidth() / 2) >= 0
                        && (lbl_documento.getLocation().x + evt.getX() - lbl_documento.getWidth() / 2) <= 350) {
                    lbl_documento.setLocation(lbl_documento.getLocation().x + evt.getX() - lbl_documento.getWidth() / 2,
                            lbl_documento.getLocation().y + evt.getY() - lbl_documento.getHeight() / 2);
                    // System.out.println(lbl_documento);
                    // System.out.println(lbl_documento.getName());
                }// para que no se salga del rango

            }
        });
        lbl_documento.addMouseListener(new MouseListener() {
            public void mouseClicked(MouseEvent evt) {
                if (evt.isMetaDown()) {
                    JL_actual = lbl_documento;
                    System.out.println(JL_actual);
                    pp_OP.show(evt.getComponent(), evt.getX(), evt.getY());
                }
            }

            public void mouseEntered(MouseEvent arg0) {

            }

            public void mouseExited(MouseEvent arg0) {

            }

            public void mousePressed(MouseEvent arg0) {
            }

            public void mouseReleased(MouseEvent arg0) {
            }
        });
    }//GEN-LAST:event_btn_documentoMouseClicked

    private void btn_InicioFinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_InicioFinMouseClicked
        JLabel lbl_inicio_fin;
        lbl_inicio_fin = new JLabel();
        lbl_inicio_fin.setOpaque(true);
        lbl_inicio_fin.getName();
        lbl_inicio_fin.setName("lbl_inicio_fin" + in_out);
        in_out++;
        //System.out.println(lbl_inicio_fin);
        //System.out.println(lbl_inicio_fin.getName());
        // System.out.println("EL ERROR ESTA AQUI");
        this.jp_Drag.add(lbl_inicio_fin);
        lbl_inicio_fin.setBackground(Color.red);
        //System.out.println(lbl_inicio_fin);
        String Nombre = lbl_inicio_fin.getName();
        lbl_inicio_fin.setLocation(10, 200);
        lbl_inicio_fin.setIcon(new ImageIcon(".\\src\\Imagenes\\UML\\in_fin.png")); // NOI18N
        lbl_inicio_fin.setMaximumSize(new java.awt.Dimension(100, 100));
        lbl_inicio_fin.setMinimumSize(new Dimension(100, 100));
        lbl_inicio_fin.setLocation(new Point(20, 20));
        lbl_inicio_fin.setPreferredSize(new Dimension(50, 50));
        lbl_inicio_fin.setSize(100, 61);
        lbl_inicio_fin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                if ((lbl_inicio_fin.getLocation().x + evt.getX() - lbl_inicio_fin.getWidth() / 2) >= 0
                        && (lbl_inicio_fin.getLocation().x + evt.getX() - lbl_inicio_fin.getWidth() / 2) <= 350) {
                    lbl_inicio_fin.setLocation(lbl_inicio_fin.getLocation().x + evt.getX() - lbl_inicio_fin.getWidth() / 2,
                            lbl_inicio_fin.getLocation().y + evt.getY() - lbl_inicio_fin.getHeight() / 2);
                    //  System.out.println(lbl_inicio_fin);
                    //System.out.println(lbl_inicio_fin.getName());
                }// para que no se salga del rango

            }
        });
        lbl_inicio_fin.addMouseListener(new MouseListener() {
            public void mouseClicked(MouseEvent evt) {
                if (evt.isMetaDown()) {
                    JL_actual = lbl_inicio_fin;
                    System.out.println(JL_actual);
                    pp_OP.show(evt.getComponent(), evt.getX(), evt.getY());
                }
            }

            public void mouseEntered(MouseEvent arg0) {

            }

            public void mouseExited(MouseEvent arg0) {

            }

            public void mousePressed(MouseEvent arg0) {
            }

            public void mouseReleased(MouseEvent arg0) {
            }
        });

    }//GEN-LAST:event_btn_InicioFinMouseClicked

    private void btn_SubProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SubProMouseClicked
        JLabel lbl_subpro;
        lbl_subpro = new JLabel();
        lbl_subpro.setOpaque(true);
        lbl_subpro.getName();
        lbl_subpro.setName("lbl_subpro" + Subpro);
        Subpro++;
        //  System.out.println(lbl_subpro);
        // System.out.println(lbl_subpro.getName());
        // System.out.println("EL ERROR ESTA AQUI");
        this.jp_Drag.add(lbl_subpro);
        lbl_subpro.setBackground(Color.red);
        // System.out.println(lbl_subpro);

        lbl_subpro.setLocation(10, 200);
        lbl_subpro.setIcon(new ImageIcon(".\\src\\Imagenes\\UML\\subpro.png")); // NOI18N
        lbl_subpro.setMaximumSize(new java.awt.Dimension(100, 100));
        lbl_subpro.setMinimumSize(new Dimension(100, 100));
        lbl_subpro.setLocation(new Point(20, 20));
        lbl_subpro.setPreferredSize(new Dimension(50, 50));
        lbl_subpro.setSize(100, 64);
        lbl_subpro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                if ((lbl_subpro.getLocation().x + evt.getX() - lbl_subpro.getWidth() / 2) >= 0
                        && (lbl_subpro.getLocation().x + evt.getX() - lbl_subpro.getWidth() / 2) <= 350) {
                    lbl_subpro.setLocation(lbl_subpro.getLocation().x + evt.getX() - lbl_subpro.getWidth() / 2,
                            lbl_subpro.getLocation().y + evt.getY() - lbl_subpro.getHeight() / 2);
                    //System.out.println( lbl_subpro);
                    // System.out.println( lbl_subpro.getName());
                }/// para que no se salga del rango

            }
        });
        lbl_subpro.addMouseListener(new MouseListener() {
            public void mouseClicked(MouseEvent evt) {
                if (evt.isMetaDown()) {
                    JL_actual = lbl_subpro;
                    System.out.println(JL_actual);
                    pp_OP.show(evt.getComponent(), evt.getX(), evt.getY());
                }
            }

            public void mouseEntered(MouseEvent arg0) {

            }

            public void mouseExited(MouseEvent arg0) {

            }

            public void mousePressed(MouseEvent arg0) {
            }

            public void mouseReleased(MouseEvent arg0) {
            }
        });
    }//GEN-LAST:event_btn_SubProMouseClicked

    private void btn_datosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_datosMouseClicked
        JLabel lbldatos;
        lbldatos = new JLabel();
        lbldatos.setOpaque(true);
        lbldatos.getName();
        lbldatos.setName("lbldatos" + datos);
        datos++;
        // System.out.println(lbldatos);
        // System.out.println(lbldatos.getName());
        // System.out.println("EL ERROR ESTA AQUI");
        this.jp_Drag.add(lbldatos);
        lbldatos.setBackground(Color.red);
        // System.out.println(lbldatos);

        lbldatos.setLocation(10, 200);
        lbldatos.setIcon(new ImageIcon(".\\src\\Imagenes\\UML\\datos.png")); // NOI18N
        lbldatos.setMaximumSize(new java.awt.Dimension(100, 100));
        lbldatos.setMinimumSize(new Dimension(100, 100));
        lbldatos.setLocation(new Point(20, 20));
        lbldatos.setPreferredSize(new Dimension(50, 50));
        lbldatos.setSize(100, 55);
        lbldatos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                if ((lbldatos.getLocation().x + evt.getX() - lbldatos.getWidth() / 2) >= 0
                        && (lbldatos.getLocation().x + evt.getX() - lbldatos.getWidth() / 2) <= 350) {
                    lbldatos.setLocation(lbldatos.getLocation().x + evt.getX() - lbldatos.getWidth() / 2,
                            lbldatos.getLocation().y + evt.getY() - lbldatos.getHeight() / 2);
                    //  System.out.println(lbldatos);
                    // System.out.println(lbldatos.getName());
                }// para que no se salga del rango

            }
        });  //agrega los label
        lbldatos.addMouseListener(new MouseListener() {
            public void mouseClicked(MouseEvent evt) {
                if (evt.isMetaDown()) {
                    JL_actual = lbldatos;
                    System.out.println(JL_actual);
                    pp_OP.show(evt.getComponent(), evt.getX(), evt.getY());
                }
            }

            public void mouseEntered(MouseEvent arg0) {

            }

            public void mouseExited(MouseEvent arg0) {

            }

            public void mousePressed(MouseEvent arg0) {
            }

            public void mouseReleased(MouseEvent arg0) {
            }
        });
    }//GEN-LAST:event_btn_datosMouseClicked

    private void btn_separadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_separadorMouseClicked
        JLabel lbl_separador;
        lbl_separador = new JLabel();
        lbl_separador.setOpaque(true);
        lbl_separador.getName();
        lbl_separador.setName("lbl_separador" + separador);
        separador++;
        // System.out.println(lbl_separador);
        // System.out.println(lbl_separador.getName());
        // System.out.println("EL ERROR ESTA AQUI");
        this.jp_Drag.add(lbl_separador);
        lbl_separador.setBackground(Color.red);
        //  System.out.println(lbl_separador);

        lbl_separador.setLocation(10, 200);
        lbl_separador.setIcon(new ImageIcon(".\\src\\Imagenes\\UML\\separador.png")); // NOI18N
        lbl_separador.setMaximumSize(new java.awt.Dimension(100, 100));
        lbl_separador.setMinimumSize(new Dimension(100, 100));
        lbl_separador.setLocation(new Point(20, 20));
        lbl_separador.setPreferredSize(new Dimension(50, 50));
        lbl_separador.setSize(6, 100);
        lbl_separador.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                if ((lbl_separador.getLocation().x + evt.getX() - lbl_separador.getWidth() / 2) >= 0
                        && (lbl_separador.getLocation().x + evt.getX() - lbl_separador.getWidth() / 2) <= 350) {
                    lbl_separador.setLocation(lbl_separador.getLocation().x + evt.getX() - lbl_separador.getWidth() / 2,
                            lbl_separador.getLocation().y + evt.getY() - lbl_separador.getHeight() / 2);
                    //   System.out.println(lbl_separador);
                    // System.out.println(lbl_separador.getName());
                }// para que no se salga del rango

            }
        });  //agrega los label
        lbl_separador.addMouseListener(new MouseListener() {
            public void mouseClicked(MouseEvent evt) {
                if (evt.isMetaDown()) {
                    JL_actual = lbl_separador;
                    System.out.println(JL_actual);
                    pp_OP.show(evt.getComponent(), evt.getX(), evt.getY());
                }
            }

            public void mouseEntered(MouseEvent arg0) {

            }

            public void mouseExited(MouseEvent arg0) {

            }

            public void mousePressed(MouseEvent arg0) {
            }

            public void mouseReleased(MouseEvent arg0) {
            }
        });
    }//GEN-LAST:event_btn_separadorMouseClicked

    private void btn_SeparadorVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SeparadorVMouseClicked
        JLabel lbl_Vseparador;
        lbl_Vseparador = new JLabel();
        lbl_Vseparador.getName();
        lbl_Vseparador.setOpaque(true);
        lbl_Vseparador.setName("lbl_Vseparador" + V_separador);
        V_separador++;
        //System.out.println(lbl_Vseparador);
        // System.out.println(lbl_Vseparador.getName());
        // System.out.println("EL ERROR ESTA AQUI");
        this.jp_Drag.add(lbl_Vseparador);
        lbl_Vseparador.setBackground(Color.red);
        //System.out.println(lbl_Vseparador);

        lbl_Vseparador.setLocation(10, 200);
        lbl_Vseparador.setIcon(new ImageIcon(".\\src\\Imagenes\\UML\\separadorV.png")); // NOI18N
        lbl_Vseparador.setMaximumSize(new java.awt.Dimension(100, 100));
        lbl_Vseparador.setMinimumSize(new Dimension(100, 100));
        lbl_Vseparador.setLocation(new Point(20, 20));
        lbl_Vseparador.setPreferredSize(new Dimension(50, 50));
        lbl_Vseparador.setSize(100, 6);
        lbl_Vseparador.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                if ((lbl_Vseparador.getLocation().x + evt.getX() - lbl_Vseparador.getWidth() / 2) >= 0
                        && (lbl_Vseparador.getLocation().x + evt.getX() - lbl_Vseparador.getWidth() / 2) <= 350) {
                    lbl_Vseparador.setLocation(lbl_Vseparador.getLocation().x + evt.getX() - lbl_Vseparador.getWidth() / 2,
                            lbl_Vseparador.getLocation().y + evt.getY() - lbl_Vseparador.getHeight() / 2);
                    //  System.out.println(lbl_Vseparador);
                    // System.out.println(lbl_Vseparador.getName());
                }// para que no se salga del rango

            }
        });  //agrega los label
        lbl_Vseparador.addMouseListener(new MouseListener() {
            public void mouseClicked(MouseEvent evt) {
                if (evt.isMetaDown()) {
                    JL_actual = lbl_Vseparador;
                    System.out.println(JL_actual);
                    pp_OP.show(evt.getComponent(), evt.getX(), evt.getY());
                }
            }

            public void mouseEntered(MouseEvent arg0) {

            }

            public void mouseExited(MouseEvent arg0) {

            }

            public void mousePressed(MouseEvent arg0) {
            }

            public void mouseReleased(MouseEvent arg0) {
            }
        });
    }//GEN-LAST:event_btn_SeparadorVMouseClicked

    private void jp_DragMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_DragMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jp_DragMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        //jLabel2.setText(JOptionPane.showInputDialog("Ingrese el nuevo texto de la Label"));
        // System.out.println(jLabel2.getText());
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jmi_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_colorActionPerformed
        try {
            JL_actual.setBackground(JColorChooser.showDialog(this, "SELECIONE UN COLOR", Color.yellow));
            System.out.println(JL_actual.getBackground());
            // this.jp_Drag.repaint();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jmi_colorActionPerformed

    private void jmi_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_textoActionPerformed
        try {
            JL_actual.setText(JOptionPane.showInputDialog("Ingrese el nuevo texto de la Label"));
            System.out.println(JL_actual.getText());
           
        } catch (Exception e) {

        }

    }//GEN-LAST:event_jmi_textoActionPerformed

    private void jmi_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarActionPerformed
        try {
            int respuesta = JOptionPane.showConfirmDialog(this.jd_UML, "Seguro que desea eliminar?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (respuesta == JOptionPane.OK_OPTION) {
                this.jp_Drag.remove(JL_actual);
                this.jp_Drag.repaint();
                JOptionPane.showMessageDialog(this.jd_UML,"Se ha eliminado correctamente");
            }

        } catch (Exception e) {

        }
    }//GEN-LAST:event_jmi_eliminarActionPerformed

    private void jmi_fuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_fuenteActionPerformed
      try {
        //   JL_actual.setFont();
           
        } catch (Exception e) {

        }
    
    }//GEN-LAST:event_jmi_fuenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Crear;
    private javax.swing.JButton btn_Crear1;
    private javax.swing.JButton btn_Decision;
    private javax.swing.JButton btn_DiagramaClases;
    private javax.swing.JButton btn_DiagramaClases1;
    private javax.swing.JButton btn_DiagramaFlujo;
    private javax.swing.JButton btn_DiagramaFlujo1;
    private javax.swing.JButton btn_InicioFin;
    private javax.swing.JButton btn_Proceso;
    private javax.swing.JButton btn_SeparadorV;
    private javax.swing.JButton btn_SubPro;
    private javax.swing.JButton btn_datos;
    private javax.swing.JButton btn_documento;
    private javax.swing.JButton btn_separador;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JDialog jd_DiagramaClases;
    private javax.swing.JDialog jd_UML;
    private javax.swing.JMenuItem jmi_color;
    private javax.swing.JMenuItem jmi_eliminar;
    private javax.swing.JMenuItem jmi_fuente;
    private javax.swing.JMenuItem jmi_texto;
    private javax.swing.JPanel jp_Drag;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JLabel lbl_Diagrama;
    private javax.swing.JLabel lbl_Diagrama1;
    private javax.swing.JLabel lbl_FondoInicio;
    private javax.swing.JLabel lbl_FondoInicio1;
    private javax.swing.JLabel lbl_UML;
    private javax.swing.JLabel lbl_UML1;
    private javax.swing.JLabel pic1;
    private javax.swing.JPopupMenu pp_OP;
    // End of variables declaration//GEN-END:variables
    private int Proceso = 0;
    private int cont_If = 0;
    private int Subpro = 0;
    private int separador = 0;
    private int V_separador = 0;
    private int in_out = 0;
    private int datos = 0;
    private int documentos = 0;
    private int Bandera = 0;
    JLabel JL_actual = null;
    // private ArrayList <JLabel> Etiquetas=new ArrayList();
/* //  new Lab();
    //pic1.setIcon(new ImageIcon("C:\\Users\\Claudia Cortes\\Desktop\\Proyecto_ClaudiaCortes_Programacion2\\Proyecto_ClaudiaCortes_Programación2\\src\\Imagenes\\avatar-1.png"));
        //pic2.setIcon(new ImageIcon("C:\\Users\\Claudia Cortes\\Desktop\\Proyecto_ClaudiaCortes_Programacion2\\Proyecto_ClaudiaCortes_Programación2\\src\\Imagenes\\bar-chart.png"));
        //pic3.setIcon(new ImageIcon("C:\\Users\\Claudia Cortes\\Desktop\\Proyecto_ClaudiaCortes_Programacion2\\Proyecto_ClaudiaCortes_Programación2\\src\\Imagenes\\battery-1.png"));
      pic1.addMouseListener(ml);
     //   pic2.addMouseListener(ml);
        //pic3.addMouseListener(ml);
        pic1.setTransferHandler(new TransferHandler("icon"));
        jLabel2.setTransferHandler(new TransferHandler("icon"));
        jLabel1.setTransferHandler(new TransferHandler("icon"));*/

}
