/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_claudiacortes_programación2;

import javax.swing.JOptionPane;

/**
 *
 * @author Claudia Cortes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        lbl_UML.setVisible(false);
        lbl_Diagrama.setVisible(false);
       // lbl_FondoInicio.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_DiagramaClases = new javax.swing.JDialog();
        jd_UML = new javax.swing.JDialog();
        btn_Proceso = new javax.swing.JButton();
        btn_Separador = new javax.swing.JButton();
        btn_Decision = new javax.swing.JButton();
        btn_SubPro = new javax.swing.JButton();
        btn_SeparadorV = new javax.swing.JButton();
        btn_InicioFin = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        canvas1 = new java.awt.Canvas();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        btn_DiagramaFlujo = new javax.swing.JButton();
        btn_DiagramaClases = new javax.swing.JButton();
        btn_Crear = new javax.swing.JButton();
        lbl_FondoInicio = new javax.swing.JLabel();
        lbl_UML = new javax.swing.JLabel();
        lbl_Diagrama = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jd_DiagramaClases.setMaximumSize(new java.awt.Dimension(600, 600));
        jd_DiagramaClases.setMinimumSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout jd_DiagramaClasesLayout = new javax.swing.GroupLayout(jd_DiagramaClases.getContentPane());
        jd_DiagramaClases.getContentPane().setLayout(jd_DiagramaClasesLayout);
        jd_DiagramaClasesLayout.setHorizontalGroup(
            jd_DiagramaClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jd_DiagramaClasesLayout.setVerticalGroup(
            jd_DiagramaClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        jd_UML.setBackground(new java.awt.Color(255, 255, 255));
        jd_UML.setMaximumSize(new java.awt.Dimension(1000, 940));
        jd_UML.setMinimumSize(new java.awt.Dimension(600, 600));
        jd_UML.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Proceso.setBackground(new java.awt.Color(255, 255, 255));
        btn_Proceso.setText("Proceso");
        btn_Proceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProcesoActionPerformed(evt);
            }
        });
        jd_UML.getContentPane().add(btn_Proceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 60));

        btn_Separador.setBackground(new java.awt.Color(255, 255, 255));
        btn_Separador.setText("Documento");
        jd_UML.getContentPane().add(btn_Separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 140, 60));

        btn_Decision.setBackground(new java.awt.Color(255, 255, 255));
        btn_Decision.setText("Decision");
        jd_UML.getContentPane().add(btn_Decision, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 140, 60));

        btn_SubPro.setBackground(new java.awt.Color(255, 255, 255));
        btn_SubPro.setText("Subproceso");
        jd_UML.getContentPane().add(btn_SubPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 140, 60));

        btn_SeparadorV.setBackground(new java.awt.Color(255, 255, 255));
        btn_SeparadorV.setText("Separador Vertical");
        jd_UML.getContentPane().add(btn_SeparadorV, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 140, 60));

        btn_InicioFin.setBackground(new java.awt.Color(255, 255, 255));
        btn_InicioFin.setText("Inicio/Finalizacion");
        jd_UML.getContentPane().add(btn_InicioFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 140, 60));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Datos");
        jd_UML.getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 140, 60));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Separador");
        jd_UML.getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 140, 60));
        jd_UML.getContentPane().add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 440, 330));

        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setText("Color");
        jd_UML.getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));
        label1.getAccessibleContext().setAccessibleName("Estilo de fuente");

        label2.setText("Fuente");
        jd_UML.getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        label3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label3.setText("Tamaño");
        jd_UML.getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));
        label3.getAccessibleContext().setAccessibleName("Tamaño");

        label4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label4.setText("Estilo de fuente");
        jd_UML.getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jMenu6.setText("Archivo");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("Insertar");
        jMenuBar2.add(jMenu7);

        jMenu8.setText("Diseño");
        jMenuBar2.add(jMenu8);

        jMenu9.setText("Datos");
        jMenuBar2.add(jMenu9);

        jMenu10.setText("Proceso");
        jMenuBar2.add(jMenu10);

        jMenu11.setText("Vista");
        jMenuBar2.add(jMenu11);

        jd_UML.setJMenuBar(jMenuBar2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_DiagramaFlujo.setBackground(new java.awt.Color(255, 255, 255));
        btn_DiagramaFlujo.setText("Diagramas de Flujo Basico");
        btn_DiagramaFlujo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DiagramaFlujoMouseClicked(evt);
            }
        });
        btn_DiagramaFlujo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DiagramaFlujoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_DiagramaFlujo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 136));

        btn_DiagramaClases.setBackground(new java.awt.Color(255, 255, 255));
        btn_DiagramaClases.setText("Diagrama de clases");
        btn_DiagramaClases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DiagramaClasesMouseClicked(evt);
            }
        });
        getContentPane().add(btn_DiagramaClases, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 160, 136));

        btn_Crear.setBackground(new java.awt.Color(255, 255, 255));
        btn_Crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        btn_Crear.setText("Crear");
        btn_Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CrearMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 170, 70));

        lbl_FondoInicio.setText("FONDO");
        getContentPane().add(lbl_FondoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 320, 340));

        lbl_UML.setText("UML");
        getContentPane().add(lbl_UML, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 320, 340));

        lbl_Diagrama.setText("Diagrama");
        getContentPane().add(lbl_Diagrama, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 320, 340));

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Insertar");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Datos");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Procesos");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Vista");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DiagramaFlujoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DiagramaFlujoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DiagramaFlujoActionPerformed

    private void btn_CrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CrearMouseClicked
        if (Bandera==0) {
            JOptionPane.showMessageDialog(this,"Debe seleccionar una opcion antes de iniciar a crear.");
        }else if (Bandera==1){
            jd_UML.show(true);
        }else if (Bandera==2){
            jd_DiagramaClases.show(true);
        }
    }//GEN-LAST:event_btn_CrearMouseClicked

    private void btn_DiagramaFlujoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DiagramaFlujoMouseClicked
        lbl_FondoInicio.setVisible(false);

        lbl_Diagrama.setVisible(false);
        lbl_UML.setVisible(true);
        Bandera = 1;
    }//GEN-LAST:event_btn_DiagramaFlujoMouseClicked

    private void btn_DiagramaClasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DiagramaClasesMouseClicked
        lbl_UML.setVisible(false);
        lbl_FondoInicio.setVisible(false);

        lbl_Diagrama.setVisible(true);
        Bandera = 2;
    }//GEN-LAST:event_btn_DiagramaClasesMouseClicked

    private void btn_ProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProcesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ProcesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Crear;
    private javax.swing.JButton btn_Decision;
    private javax.swing.JButton btn_DiagramaClases;
    private javax.swing.JButton btn_DiagramaFlujo;
    private javax.swing.JButton btn_InicioFin;
    private javax.swing.JButton btn_Proceso;
    private javax.swing.JButton btn_Separador;
    private javax.swing.JButton btn_SeparadorV;
    private javax.swing.JButton btn_SubPro;
    private java.awt.Canvas canvas1;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JDialog jd_DiagramaClases;
    private javax.swing.JDialog jd_UML;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JLabel lbl_Diagrama;
    private javax.swing.JLabel lbl_FondoInicio;
    private javax.swing.JLabel lbl_UML;
    // End of variables declaration//GEN-END:variables
private int Bandera=0;
}
